-- Additional questions to expand the question bank
-- Run this after the initial data.sql to add more questions

INSERT IGNORE INTO questions (skill_id, question_text, difficulty_level, expected_keywords, level_indicators, suggested_answer_length, context_hint) VALUES
(1, 'How do you handle exceptions in Spring Boot applications?', 2.0, '["@ExceptionHandler", "@ControllerAdvice", "GlobalExceptionHandler", "ResponseEntityExceptionHandler"]', '{"2": ["@ExceptionHandler"], "3": ["@ControllerAdvice", "custom exceptions"], "4": ["error responses", "logging"]}', 180, 'Focus on global exception handling patterns.'),
(1, 'Explain dependency injection in Spring Framework.', 1.5, '["@Autowired", "@Component", "@Service", "@Repository", "IoC"]', '{"1": ["@Autowired"], "2": ["constructor injection", "setter injection"], "3": ["@Component", "@Service"]}', 150, 'Describe the concept and different types of injection.'),
(2, 'What are the main HTTP status codes you use in REST APIs?', 1.0, '["200", "201", "400", "401", "404", "500"]', '{"1": ["200 OK", "404 Not Found"], "2": ["201 Created", "400 Bad Request"], "3": ["401 Unauthorized", "500 Internal Server Error"]}', 120, 'List common status codes and their meanings.'),
(2, 'How do you implement pagination in a REST API?', 2.5, '["Pageable", "Page", "Slice", "Spring Data", "offset", "limit"]', '{"2": ["Pageable", "Page"], "3": ["custom pagination", "sorting"], "4": ["performance optimization"]}', 200, 'Consider both Spring Data and custom implementations.'),
(3, 'Explain the difference between INNER JOIN and LEFT JOIN.', 1.5, '["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "NULL values"]', '{"1": ["INNER JOIN returns matching", "LEFT JOIN includes all from left"], "2": ["NULL values in LEFT JOIN"]}', 130, 'Use a simple example to illustrate the difference.'),
(3, 'How do you create indexes in SQL and when should you use them?', 2.0, '["CREATE INDEX", "performance", "WHERE clause", "JOIN columns"]', '{"2": ["CREATE INDEX syntax", "index on WHERE columns"], "3": ["composite indexes", "index maintenance"]}', 170, 'Explain the syntax and best practices.'),
(4, 'Describe the main components of a microservices architecture.', 3.0, '["service discovery", "API gateway", "circuit breaker", "distributed tracing"]', '{"3": ["service registry", "API gateway", "circuit breaker"], "4": ["distributed logging", "container orchestration"]}', 220, 'Explain how these components work together.'),
(4, 'How do you handle distributed transactions in microservices?', 4.0, '["saga pattern", "two-phase commit", "eventual consistency", "compensating transactions"]', '{"4": ["saga pattern", "compensating transactions"], "5": ["event sourcing", "CQRS"]}', 250, 'Compare different approaches and their trade-offs.'),
(5, 'Explain the difference between EC2 and Lambda in AWS.', 2.0, '["EC2", "Lambda", "serverless", "virtual machines", "functions"]', '{"2": ["EC2 is VMs", "Lambda is serverless"], "3": ["pricing models", "scaling"]}', 160, 'Compare use cases and cost implications.'),
(5, 'How do you secure an S3 bucket?', 2.5, '["bucket policy", "IAM", "encryption", "public access block"]', '{"2": ["bucket policies", "IAM roles"], "3": ["encryption", "versioning"], "4": ["VPC endpoints", "CloudTrail"]}', 190, 'Cover access control, encryption, and monitoring.'),
(6, 'Explain the difference between Docker and Kubernetes.', 2.5, '["Docker", "container", "Kubernetes", "orchestration", "pods"]', '{"2": ["Docker creates containers", "Kubernetes orchestrates"], "3": ["pods", "services", "deployments"]}', 180, 'Describe their roles in containerized applications.'),
(6, 'How do you scale applications in Kubernetes?', 3.5, '["HorizontalPodAutoscaler", "Cluster Autoscaler", "replicas", "load balancing"]', '{"3": ["replicas", "HPA"], "4": ["Cluster Autoscaler", "node pools"], "5": ["custom metrics", "operator pattern"]}', 230, 'Explain different scaling strategies and when to use them.'),
(7, 'What are the different types of testing in software development?', 1.5, '["unit testing", "integration testing", "system testing", "acceptance testing"]', '{"1": ["unit", "integration"], "2": ["system", "acceptance"], "3": ["performance", "security"]}', 140, 'List and briefly describe each type.'),
(7, 'How do you write effective unit tests?', 2.5, '["Arrange-Act-Assert", "mocking", "edge cases", "test coverage"]', '{"2": ["AAA pattern", "mocking"], "3": ["test doubles", "parameterized tests"], "4": ["TDD", "mutation testing"]}', 200, 'Focus on best practices and common patterns.'),
(8, 'Explain the Git rebase vs merge workflow.', 2.0, '["git rebase", "git merge", "linear history", "merge commits"]', '{"2": ["rebase rewrites history", "merge preserves history"], "3": ["interactive rebase", "merge strategies"]}', 170, 'Compare the workflows and their use cases.'),
(8, 'How do you resolve merge conflicts in Git?', 2.0, '["git status", "git add", "git commit", "conflict markers"]', '{"2": ["identify conflicts", "edit files", "git add"], "3": ["git mergetool", "prevent conflicts"]}', 160, 'Walk through the resolution process step by step.'),
(9, 'Describe your approach to debugging a complex issue.', 2.5, '["reproduce", "isolate", "hypothesis", "logs", "breakpoints"]', '{"2": ["reproduce issue", "add logging"], "3": ["isolate components", "unit tests"], "4": ["performance profiling", "root cause analysis"]}', 210, 'Explain your systematic debugging process.'),
(9, 'How do you optimize algorithm performance?', 3.5, '["Big O", "time complexity", "space complexity", "trade-offs"]', '{"3": ["analyze complexity", "identify bottlenecks"], "4": ["algorithm selection", "data structures"], "5": ["parallelization", "caching"]}', 240, 'Discuss analysis techniques and optimization strategies.'),
(10, 'How do you explain a complex technical concept to a non-technical person?', 2.0, '["analogy", "simplification", "examples", "visualization"]', '{"2": ["use analogies", "avoid jargon"], "3": ["step-by-step explanation", "check understanding"]}', 180, 'Focus on communication techniques and examples.');
